// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEVKbxtj2RprmlHJws84pqQP_uXiHnOIo',
    appId: '1:225007829513:web:0e1ed10568578365846ed8',
    messagingSenderId: '225007829513',
    projectId: 'aviacaoparanapanema',
    authDomain: 'aviacaoparanapanema.firebaseapp.com',
    storageBucket: 'aviacaoparanapanema.appspot.com',
    measurementId: 'G-B7R934GCTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD2qnPI0HASF2HTVHnwcNRSx9mQxm2GFQ',
    appId: '1:225007829513:android:82745feee2c1024d846ed8',
    messagingSenderId: '225007829513',
    projectId: 'aviacaoparanapanema',
    storageBucket: 'aviacaoparanapanema.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp1JKj6Zf5z-RZ5gVUWKXk4CauOt-mKiU',
    appId: '1:225007829513:ios:c1eb971a0f7f4074846ed8',
    messagingSenderId: '225007829513',
    projectId: 'aviacaoparanapanema',
    storageBucket: 'aviacaoparanapanema.appspot.com',
    iosClientId: '225007829513-mqpm6qe5odbamfmd2kure0flk5m13s1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.aviacaoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp1JKj6Zf5z-RZ5gVUWKXk4CauOt-mKiU',
    appId: '1:225007829513:ios:c1eb971a0f7f4074846ed8',
    messagingSenderId: '225007829513',
    projectId: 'aviacaoparanapanema',
    storageBucket: 'aviacaoparanapanema.appspot.com',
    iosClientId: '225007829513-mqpm6qe5odbamfmd2kure0flk5m13s1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.aviacaoApp',
  );
}
